### ISSUE TITLE
Improve Transaction details pop up

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react-native#13]
Hi Rafee,
Please implement the below changes for the transaction details pop up:

![page_2](https://user-images.githubusercontent.com/22153546/36486436-298b9baa-1727-11e8-8c75-d164d284064f.png)

1. Add an "x" in the top right - when a user taps this it closes the pop up. Tapping anywhere else other than the pop-up also closes it.
2. Make the pop-up pane slightly less wide so that it does not touch the sides of the screen.
3. Add "Transaction details" heading at the top.
4. Display the transaction type (debit/credit)
5. Display the total amount (this is the amount + fees)
6. Below the total amount display the breakdown of the amount and fees
7. Display what a user's balance was after this transaction
8. The date and the status remain the same
9. Please change amounts to show the - symbol before the currency symbol. So instead of $-2.00 we should display -$2.00.

Please take note of all of the spacing :)

Shout if you have any questions

**Comment by Cupofassam** [comment]
Thanks Rafee!

The styling is looking a bit off on my phone (Huawei P9 Lite) - please see the screenshot below and make the necessary adjustments.

![image](https://user-images.githubusercontent.com/22153546/36753676-923e1ea6-1c0f-11e8-8145-33d625f9dd2f.png)

**Comment by Cupofassam** [comment]
Hey Rafee,
This is still not looking right. In the below image, the image on the left is the design and the image on the right is what it looks like on my phone. My feedback:

![image](https://user-images.githubusercontent.com/22153546/36982884-a413ee06-2099-11e8-9e48-15cab95eea98.png)

1. The headings font is too big - the font size I used was 20px.
2. "Total amount" is still showing on 2 lines, it needs to show on one line. The font size is also too big - I used 24px size (same for Type and balance).
3. "Amount" and "Fees" font is too big - I used size 20px.
4. The spacing between the $1 and "Balance" is too little (same for Type, total amount, amount, and fees). Please make it the same as the design.
5, 6. There is too much space above and below the transaction date/time.
7. The grey lines between Amount and Fees are missing.

**Comment by Cupofassam** [comment]
This is correct on the transactions page you swipe to from the home page, but not on the transactions page you get to from the menu. This should be the same page.

**Comment by m-deacon** [comment]
Overall I'm quite happy with how this ticket turned out. I know I will want to revisit it slightly when I understand styling a bit better, but for now I think it's good.

Note: I've had to remove the close "X" top right for now. Will add it back once I understand how to do the styling (should be next week).

**Comment by Cupofassam** [comment]
This might just be my phone, but the only thing I would change if we can do it quickly is to move the content to be more central:

![image](https://user-images.githubusercontent.com/22153546/38730697-da3398c8-3f17-11e8-899a-62bf533f9504.png)

There's quite a big gap at the top vs from the bottom

**Comment by Cupofassam** [comment]
Noticed it only shows currency symbol and the first number, it should show decimal places for a currency if there are any, so above should show $0.00 and $2.00 etc

There is some currency function in the app somewhere that is used to convert money values into decimal structure

**Comment by Cupofassam** [comment]
Looks great Matt, can merge :)
