### ISSUE TITLE
Displaying reward status

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react-native#146]
Hey M, tagging @Stephan-e in this as well

On the list of claimed rewards, when we display the status, when it's accepted it just says `accept` - it looks like something we need to tap in order to accept it instead of telling us that it is accepted. @m-deacon I assume you're just displaying whatever status Stephan sends through? If yes, @Stephan-e could we change this from 'accept' to say 'accepted'?

@m-deacon can you make the status green if it's accept/ed ? Pending could maybe be grey or red.

![whatsapp image 2018-10-22 at 18 31 31 1](https://user-images.githubusercontent.com/22153546/47305531-070c0980-d62a-11e8-86a1-6e51a0e915d9.jpeg)

**Comment by Stephan-e** [comment]
sure, no problem. I can make it return "accepted"

**Comment by m-deacon** [comment]
Before making back-end changes on this, would you (@Cupofassam) not prefer it say "Accepted" with a capital? Cause if that's the case then I could just create a dictionary on the mobile side that maps "accept" to "Accepted", "fail" to "Failed" etc. 

For this approach, @Stephan-e could you just provide the list of current status string values please?

**Comment by Cupofassam** [comment]
"Accepted" or "accepted" are both okay I think. We could do the dictionary method - I'm just wary of doing this type of thing because it can become difficult to maintain. For example we try to avoid doing it for errors - backend ideally must make a human-readable error which can be displayed on the frontend rather than frontend having to translate it. So I'm taking a similar approach with statuses - but perhaps this is a small enough thing that it's okay. @OdinsPlasmaRifle thoughts?

**Comment by m-deacon** [comment]
Yeah - 100% agree with preferring it coming from the back-end as the correct label. I can even just add a function my side that capitalises the first letter of whatever server response comes back. 

I'm going to implement it like this for now and we can iterate.
