### ISSUE TITLE
Slightly cramped card text

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react-native#147]
Hey M

What is the line spacing on this? Looks a little tight somehow

![whatsapp image 2018-10-22 at 18 25 11](https://user-images.githubusercontent.com/22153546/47306053-a087eb00-d62b-11e8-81d5-b38fd97da75f.jpeg)

**Comment by m-deacon** [comment]
Increased lineHeight to 22 - let me know if you want it more
