### ISSUE TITLE
Centre active field on registration form

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react-native#17]
Hi Rafee,

On the registration form, if I select a field that sits lower than where my keyboard would appear, the app scrolls to the field and places it at the bottom of my visible screen with the keyboard open, like this (going to use the "Email" field for both examples):

![image](https://user-images.githubusercontent.com/22153546/36532291-fb089e34-17c8-11e8-8f6a-cf41bab9268a.png)

Can you please change this so that the active field that a user has selected appears in the middle of the visible screen, like this:

![image](https://user-images.githubusercontent.com/22153546/36532308-04c7a230-17c9-11e8-8bdd-3f1392ac13d9.png)

So the form should scroll upwards as a user selects a field. Another example:

![image](https://user-images.githubusercontent.com/22153546/36532487-8b3d9338-17c9-11e8-95d3-cf6f2d8ffbc0.png)

Let me know if you have anyquestions

**Comment by tsmrafee-bs** [comment]
with the signup button over the keyboard, it is not possible to take the focused text input in the center.

**Comment by Cupofassam** [comment]
Let's put it at the bottom of the form instead of making it sticky, so users must scroll down to it to submit the form.

**Comment by Cupofassam** [comment]
30% done

**Comment by Cupofassam** [comment]
Thanks Rafee, this works nicely when the keyboard is open. The only issue I spot is when a user first lands on the page and their keyboard is closed. When they tap on a field, it opens the field at the top of the keyboard rather than in the middle. Is there a way to make a field centre when first tapped and the keyboard is closed?

Thanks

**Comment by Cupofassam** [comment]
Makes sense - okay, it's definitely an improvement so we can use this still.

**Comment by Cupofassam** [comment]
Can be merged into `master`

**Comment by Cupofassam** [comment]
Redoing this in this issue https://github.com/rehive/wallet-react-native/issues/74
