### ISSUE TITLE
Improve registration form validation errors

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react-native#19]
Hi Rafee,

I want to make the validation on the registration page more user-friendly. Some general principles for this:

- No more pop-ups to display errors, we'll display errors inline
- We are going to use both front-end and back-end/API validation

Display frontend validation where you can display errors without posting to the API. This will be the case for the following:

- Email format - standard email validation e.g. x@y.c
- Mobile format - please use this for this validation - https://github.com/googlei18n/libphonenumber 
- Email is blank
- Company is blank
- Password blank
- Confirm password blank
- Confirm password does not match password
- Terms of use false
- Password minimum length

Use backend validation where you return the API error for the following:

- Email is not unique
- Mobile is not unique
- Company does not exist

I would like the validation to trigger at different points depending on what a user is entering.

The following should validate after a user has typed in data and moved away from the field:

- Email format
- Mobile format
- Password length
- Confirm password does not match password

The rest of the validation should only trigger once the user taps the register button:

- Email blank
- Company blank
- Password blank
- Confirm password blank
- Terms of use false
- Email is not unique
- Company does not exist

Here is a list of what the errors should be and whether it comes from the API or not:

Validation case | Error message | Source of error copy
------------ | ------------- | -------------
Email format | Enter a valid email address. | Frontend
Mobile format | Enter a valid mobile number. | Frontend
Email is blank | Enter a valid email address. | Frontend
Company is blank | Enter a valid company id. | API
Password blank | Password must be at least 8 characters. | Frontend
Confirm password blank | Confirm your password. | Frontend
Confirm password does not match password | Passwords do not match. | Frontend
Terms of use false | Please accept the terms of use. | Frontend
Password minimum length | Password must be at least 8 characters. | Frontend
Email is not unique | A user is already registered with this email address. | API
Mobile is not unique | A user is already registered with this mobile number. | API
Company does not exist | Enter a valid company id. | API

Designs with examples:

![validation on app](https://user-images.githubusercontent.com/22153546/36545134-ebd19812-17f0-11e8-9347-574d91245be4.png)

**Comment by Cupofassam** [comment]
Did some testing and found some issues:

1. On register, I entered a password 9 characters long and got an error telling me it must be at least 8 characters. The password I entered should not have triggered a minimum length error. 
2. On register, I entered an email address with the format of name+word@email.com and it gave me a "Please enter a valid email address" error. The email I entered should not have triggered this error.
3. I changed my email address and got a "A user is already registered with this address" error. In the company I selected, there is no user with this email address so I should not have gotten this error. 
4. The A user is already registered with this address" error is cutting off on my phone - it should wrap to the next line if there is not enough space.

![whatsapp image 2018-03-05 at 11 28 18](https://user-images.githubusercontent.com/22153546/36967434-69907654-2068-11e8-963c-d2d233cfe4e2.jpeg)

5. I got an error "Enter a valid company id", but the company ID I entered was valid.
6. I did not enter a mobile number but got the error "A user is already registered with this mobile number" - I should not get this error with a blank mobile error. The error also cuts off, see image above.
7. When I encounter a valid error, such as leaving email blank, if I am scrolled down to the bottom of the page and tap "Register", if there is an error, the app should scroll my page up to where the error is.

**Comment by m-deacon** [comment]
I tackled this in Issue55. Please note though, that there is no way to run validation if someone clicks to the next field, I have however added validation if they use the "next" button on the keyboard. These next buttons should also all work now.
