### ISSUE TITLE
Duplicating contacts + spacing issues

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react-native#24]
Hi Rafee,

## Issue 1. 
When I try to send and the app gets my contacts, it shows a lot of duplicates even though they are not duplicates in my contacts. Sometimes I see the same person 4 times.

It takes the number and spaces it differently. So one number will look like this

+27 XX XXX XXXX

and the next will be

+27XXXXXXXXX

See below:

![image](https://user-images.githubusercontent.com/22153546/37001418-1e66e674-20cf-11e8-81c9-5a76803f2fe2.png)

## Issue 2. 
The spacing between the image on the left and the name on the right is a bit too much, please decrease it by half.

## Issue 3.
 If possible, the contact image on the left should pull from an contact's profile image on a user's phone.

**Comment by Cupofassam** [comment]
Hey Rafee, please see my feedback below:

### Issue 1

I'm still getting duplicate contacts. In my actual contacts list, I don't have duplicates of these contacts, so the app is creating duplicates for some reason - please fix this.

### Issue 2

This spacing is fine, thanks.

### Issue 3

I added a contact profile image but it's not pulling through - is it possible to add this? I'm testing on a Huawei P9 Lite.

**Comment by tsmrafee-bs** [comment]
for the issue 3, you have to refresh the contacts by pulling the scroll view

**Comment by Cupofassam** [comment]
Cool! When I refreshed the profile image pulled through and the contacts no longer duplicate - thanks Rafee :)

**Comment by Cupofassam** [comment]
This is working fine but loads quite slowly now, we should look at optimizing this page in future,

**Comment by Cupofassam** [comment]
https://github.com/rehive/wallet-react-native/issues/41
