### ISSUE TITLE
KYC review and update

### ISSUE THREAD

**Issue by Cupofassam** [rehive/wallet-react-native#27]
The Basic Info and Address KYC statuses are broken on the Get Verified page - they just show little circles rather than a status.

![image](https://user-images.githubusercontent.com/22153546/37156428-bdfa4a5c-22ee-11e8-857e-5c31484de864.png)

**Comment by m-deacon** [comment]
Hi @Cupofassam,

So I added a dummy "Pending" as a status when the app can't find a success / incomplete response from looking at the API. This however isn't a pretty solution, but looking at the code there isn't much standardisation of how this is handled. This solution does fix the empty circles problem though and shouldn't affect the implementation beyond when the empty circles would've popped up.
