### ISSUE TITLE
Send verify mobile is not re-sending OTP

### ISSUE THREAD

**Issue by Helghardt** [rehive/wallet-react-native#46]
The resend verify mobile on the signup flow is not re-sending an OTP, but incorrectly sending an email.

1. The below image is a suggestion of how we can add support to view and change mobile number if needed. Users sometimes type the wrong mobile number.

2. Resend option should appear after 30 seconds.

<img width="350" alt="screen shot 2018-04-09 at 10 31 30 pm" src="https://user-images.githubusercontent.com/5997897/38521405-e1060f52-3c45-11e8-9696-423be1556905.png">

**Comment by Cupofassam** [comment]
Hey Rafee,

I navigated to Settings, Mobile numbers, and added a mobile number. After that the screen went blank and I couldn't do anything. I did get the OTP. I went back and the app seemed to reload. I navigated back to settings, mobile numbers and saw my added mobile number. I tapped verify and it sent me another OTP and then came up with this screen:

![whatsapp image 2018-04-17 at 23 38 14](https://user-images.githubusercontent.com/22153546/38899663-f1eca1ce-4298-11e8-8807-a67986d35f85.jpeg)

I tried to register and included a mobile number but was not able to register - I tapped the register button but nothing happened.

**Comment by Cupofassam** [comment]
Do I need to npm install? When I try to register it just scrolls back up to my mobile number I entered. It doesn't register or show an error or anything.

It seems to be getting stuck and not send my phone number.In terminal I can usually see my email address and then the object send through with my company, email, first name etc. But on this branch in terminal all I see is my email address, the object isn't being sent. 

I also get a mounting error, not sure if it's related:

![image](https://user-images.githubusercontent.com/22153546/38987228-4d24fb86-43cf-11e8-904a-4e06465e8f62.png)
